unbridged camera
Sunoo/homebridge-camera-ffmpeg pull request #1205
Opened 2021-09-28 19:31 UTC by yjeanrenaud

added details on how to install an unbridged camera in Apple HomeKit

2021-09-30 18:07 UTC, jgrimard requested changes
Thank you.  Your instructions worked great.  I just used them on iOS15.  
Please change the following line:
```
Then select `Add device` and let the app search for nearby devices not yet bound to the HomeKit instance.
```
to
```
Then select `Add Accessory`, click `More options...` and let the app search for nearby devices not yet bound to the HomeKit instance.
```

2021-09-30 19:19 UTC, yjeanrenaud commented
Thanks! I missed to check the English localisation of the dialogue.

2021-09-30 20:02 UTC, jgrimard approved these changes

2025-01-27 01:17 UTC, donavanbecker commented
All cameras are forced unbridged in v4.0.0

2025-01-27 01:17 UTC, closed without merging